(() => {
  const q=(s,r=document)=>r.querySelector(s), qa=(s,r=document)=>[...r.querySelectorAll(s)];
  const say=(message)=>typeof toast==='function'?toast(message):null;

  const criteria=[
    {key:'Language',sub:'Hard knock-out',title:'Is the notice in a language Aceso can act on?',purpose:'Screen out notices in languages the team cannot realistically respond to, before spending any LLM budget on them.',settings:['English','Spanish','Portuguese','French — conditional (min. 60% fit)'],agent:[['Detect the language','Reads the notice language directly from the source record — pure code, no LLM needed for English, Spanish or Portuguese.'],['Score French conditionally','A French-only notice still gets a real LLM fit score instead of an automatic pass — a keyword-only score used to dump every French notice into review at 0%, since the topic dictionary is only in English/Spanish.'],['Apply the French gate','Below 60% fit, discard with the reason visible. At or above 60%, always route to human review — never straight to Recommended — until someone confirms the team has French-language delivery capacity.']],human:[['Confirm delivery languages','Approves which languages the team can realistically deliver in this cycle.'],['Confirm French capacity','Reviews French notices that clear the 60% gate and decides whether to pursue.']],rule:'A notice in any language other than English, Spanish or Portuguese is knocked out automatically — except French, which is scored normally and gated at 60% fit instead of discarded outright.',example:'A French-language EOI scores 74% on thematic fit. It clears the 60% gate and goes to human review — never straight to Recommended — because no scoring model can confirm French delivery capacity on its own.'},
    {key:'Geography',sub:'Delivery context',title:'Where can Aceso credibly deliver?',purpose:'Define the countries and regions where experience, eligibility and a viable partner route make delivery realistic.',settings:['Africa','Latin America','East Africa','Multi-country allowed'],agent:[['Extract geography','Reads the country, region and multi-country scope from the full notice.'],['Flag eligibility red flags','Scans the prose for "national firms/consultants only" clauses, in-country incorporation requirements, region-only eligibility (e.g. EU firms only) and specific educational or credential requirements.'],['Flag exceptions','Keeps consortium and subcontracting routes open instead of rejecting them automatically.']],human:[['Confirm priorities','Updates the markets the team wants to pursue this cycle.'],['Validate partner route','Confirms whether Aceso can participate through a local partner.']],rule:'“National firm only” is not an automatic exclusion when consortiums or subcontracting are permitted — eligibility red flags are read by the LLM, not hard-coded, because they are written in ambiguous prose.',example:'A Rwanda notice requires local registration but accepts consortiums. The agent keeps it in review and asks the analyst to validate a partner route.'},
    {key:'Expertise',sub:'Strategic alignment',title:'Does the scope match Aceso’s work?',purpose:'Compare the actual objectives and deliverables with Aceso’s proven health-systems and advisory experience.',settings:['Health financing','Provider payment systems','UHC & health systems reform','Primary care & MNCH','PPPs & private sector role','Governance','Health IT / digital health','Pandemic preparedness (PPR) & One Health'],agent:[['Read the full scope','Uses objectives, deliverables and eligibility—not the title alone.'],['Match evidence','Compares the scope with prior proposals, projects and deliverables.'],['Score relevance','Separates core fit, adjacent fit and out-of-scope work.']],human:[['Maintain pillars','Approves the expertise areas the agent should recognize.'],['Review edge cases','Decides when an adjacent topic is strategically worth pursuing.']],rule:'A keyword match never overrides the actual deliverables or applicant type.',example:'A tender mentions “health systems” but only purchases equipment. The agent classifies the deliverables as procurement, not advisory work.'},
    {key:'Opportunity type',sub:'Procurement fit',title:'Is this the kind of work Aceso pursues?',purpose:'Prioritize advisory assignments and remove procurement that does not require Aceso’s service model.',settings:['RFP / consulting','EOI','Technical assistance','Grants','Firm only (individual: $40K+ exception)'],agent:[['Classify the notice','Identifies RFP, EOI, grant, tender or individual consultancy.'],['Inspect deliverables','Separates advisory work from goods, construction and logistics.'],['Apply knock-outs','Records the exact exclusion rule and supporting evidence.']],human:[['Set acceptable types','Chooses which opportunity types remain monitored.'],['Recover exceptions','Returns a questionable exclusion to human review.']],rule:'Exclude goods, civil works and warehousing notices outright. An individual-consultant notice is excluded by default too — the only way it survives is the Economics knock-out’s $40K, focus-country exception.',example:'A hospital equipment tender is excluded as procurement of goods, with the exact source passage preserved for audit.'},
    {key:'Economics',sub:'Value & effort',title:'Is the opportunity economically viable?',purpose:'Balance potential value with proposal effort, delivery complexity and strategic importance.',settings:['Minimum $200K (firm)','$40K+ individual (focus country)','$200K–$2M','$2M–$10M'],agent:[['Capture value','Extracts budget, currency and whether the amount is undisclosed.'],['Apply the knock-out','A firm contract below $200,000 is discarded before any LLM scoring; an individual-consultant notice only survives when it is highly relevant or in a focus country AND above $40,000.'],['Estimate effort','Flags likely proposal and delivery load from duration and deliverables.']],human:[['Set thresholds','Defines the $200K / $40K minimums and which countries count as a focus country.'],['Approve exceptions','Keeps strategically important work outside the standard range.']],rule:'A firm contract must exceed $200,000 USD. An individual consultant only passes the knock-out when highly relevant or in a focus country AND above $40,000 USD — an undisclosed value means “needs review,” never automatic rejection.',example:'A $180,000 individual-consultant assignment in Kenya — a focus country — clears the $40K individual threshold. The same $180,000 from a consulting firm would be knocked out for falling under the $200K firm minimum.'},
    {key:'Timing',sub:'Deadline & capacity',title:'Can the team respond and deliver?',purpose:'Surface deadlines early enough for a quality pursuit and avoid commitments the team cannot staff.',settings:['31–90 days','3–6 months','Flag under 14 days','Capacity check'],agent:[['Calculate time','Counts working days and identifies clarification deadlines.'],['Assess complexity','Compares remaining time with required partners and documents.'],['Check capacity','Flags overlap with active proposals and delivery load.']],human:[['Confirm availability','Validates owner, reviewers and technical leads.'],['Make the trade-off','Chooses which pursuit receives capacity when deadlines collide.']],rule:'A short deadline is excluded only when the required preparation cannot reasonably be completed.',example:'Two proposals close in the same week. The agent shows the collision; Business Development assigns priority and ownership.'},
    {key:'Decision',sub:'Human checkpoints',title:'When must a human decide?',purpose:'Keep every recommendation traceable while reserving pursuit, staffing and submission decisions for people.',settings:['Analyst review','BD recommendation','Finance check','Director approval'],agent:[['Prepare evidence','Shows source fields, fit, warnings and reusable experience.'],['Explain uncertainty','Labels missing, conflicting or assumption-based information.'],['Route the case','Assigns the next decision and preserves comments and history.']],human:[['Go / no-go','Approves pursuit or keeps the opportunity excluded.'],['Resolve ambiguity','Validates partners, budget and team.'],['Approve submission','Reviews the generated draft before it is sent.']],rule:'The agent recommends and documents. It never makes the final pursuit or submission decision.',example:'The agent prepares a proposal preview, but the analyst must review it and the director must authorize submission.'},
    {key:'Sources',sub:'Intelligence feeds',title:'Where does each opportunity come from?',purpose:'Three feeds validate every notice before it reaches the pipeline, each connected a different way and held to a different trust level.',settings:['Grants.gov (API)','DevelopmentAid (private feed)','Coefficient Giving (RFP monitor)','Priority: Global Health & Wellbeing Opportunities'],agent:[['Grants.gov','Pulls notices directly through the public API — no manual step, refreshed on every scheduled search.'],['DevelopmentAid','Imports from a saved search, export or alert once Liz confirms the membership tier supports it.'],['Coefficient Giving — monitor scope','Watches coefficientgiving.org/research-and-news/ and prioritizes the Global Health & Wellbeing Opportunities section; blogs, funding news and general research are discarded automatically — only requests for proposals are kept.'],['Coefficient Giving — field extraction','For every RFP kept, extracts title, objective, amount, eligibility, deadline and the official link back to the notice.']],human:[['Confirm DevelopmentAid access','Verify membership tier, and whether saved searches, exports or alerts are available.'],['Review a saved search example','Ask for one existing DevelopmentAid saved search so the agent can match its filters.'],['Confirm monitored pages','Approve the exact Coefficient Giving section(s) the agent should watch.'],['Resolve conflicting criteria','Some terms — like MNCH — appear both as a priority topic and a possible exclusion keyword; confirm which rule wins before enabling the feed.'],['Authorize the pilot','Approve using all three sources together for the trial period.']],rule:'A Coefficient Giving notice only enters the pipeline when classified as one of the four statuses below — never from an unclassified news or blog page.',example:'A Global Health & Wellbeing Opportunities post announces a future funding round with no submission process yet. The agent tags it “Potential Future Opportunity” and keeps it visible without asking for a pursuit decision.',legend:[['rfp-open','Open RFP','Accepting proposals now — enters the pipeline for review.'],['rfp-closed','Closed RFP','Submission window has passed — kept for reference, not pursuit.'],['rfp-info','Informational Announcement','Funder context or guidance — no submission process yet.'],['rfp-potential','Potential Future Opportunity','Signals a likely future round — watch, no action required yet.']]}
  ];
  let criterion=0, owner='agent';

  function renderNotebook(){
    const view=q('#criteriaView'),s=criteria[criterion]; if(!view)return;
    view.innerHTML=`<header class="notebook-head"><div><p class="eyebrow">SEARCH & DECISION CRITERIA</p><h1>How the opportunity agent works</h1><p>A guided notebook for configuring the agent and understanding exactly where human judgment begins.</p></div><aside><b>LIVE PILOT</b><strong>9</strong><span>ready for review</span><small>37 excluded with traceable reasons</small></aside></header>
      <section class="criteria-notebook"><i class="ring r1"></i><i class="ring r2"></i><i class="ring r3"></i><i class="ring r4"></i>
        <article class="notebook-page settings-page"><p class="page-count">CRITERION 0${criterion+1} <span>/ 08</span></p><h2>${s.title}</h2><p>${s.purpose}</p><h3>Current pilot settings</h3><div class="notebook-settings">${s.settings.map(x=>`<button class="selected"><span>✓</span>${x}</button>`).join('')}</div><div class="rule-note"><small>DECISION RULE</small><b>${s.rule}</b></div>${s.legend?`<div class="rfp-legend"><small>RFP CLASSIFICATION</small>${s.legend.map(x=>`<div><span class="tag rfp-status ${x[0]}">${x[1]}</span><p>${x[2]}</p></div>`).join('')}</div>`:''}</article>
        <article class="notebook-page playbook-page"><div class="owner-tabs"><button data-owner="agent" class="${owner==='agent'?'active':''}">Agent</button><button data-owner="human" class="${owner==='human'?'active':''}">Human</button></div><p class="eyebrow">${owner==='agent'?'WHAT THE AGENT DOES':'WHAT THE REVIEWER DECIDES'}</p><h2>${owner==='agent'?'Automated screening playbook':'Required human checkpoints'}</h2><div class="notebook-actions">${s[owner].map((x,i)=>`<div><i>${i+1}</i><span><b>${x[0]}</b><p>${x[1]}</p></span></div>`).join('')}</div><aside class="worked-example"><small>WORKED EXAMPLE</small><p>${s.example}</p><b>${owner==='agent'?'Agent output: documented recommendation':'Human output: recorded decision'}</b></aside></article>
      </section><footer class="notebook-footer"><button id="criterionPrev" ${criterion===0?'disabled':''}>← Previous</button><nav>${criteria.map((x,i)=>`<button data-criterion="${i}" class="${i===criterion?'active':i<criterion?'done':''}"><i>${i<criterion?'✓':i+1}</i><span>${x.key}</span></button>`).join('')}</nav><button id="criterionNext">${criterion===7?'Save criteria':'Next criterion →'}</button></footer>`;
    qa('[data-owner]').forEach(b=>b.onclick=()=>{owner=b.dataset.owner;renderNotebook()});
    qa('[data-criterion]').forEach(b=>b.onclick=()=>{criterion=Number(b.dataset.criterion);owner='agent';renderNotebook()});
    q('#criterionPrev').onclick=()=>{if(criterion){criterion--;owner='agent';renderNotebook()}};
    q('#criterionNext').onclick=()=>{if(criterion<7){criterion++;owner='agent';renderNotebook()}else say('Criteria saved and applied to the next agent search.')};
    qa('.notebook-settings button').forEach(b=>b.onclick=()=>b.classList.toggle('selected'));
  }

  function tuneToday(){
    const headline=q('#todayView .hero-copy h1');
    if(headline) headline.innerHTML='<strong class="today-nine">9</strong> opportunities ready<br>for review today';
    const tools=q('#todayView .section-title.compact .table-tools');
    if(tools&&!q('.search-wrap',tools)){
      const input=q('input',tools),wrap=document.createElement('label');wrap.className='search-wrap';input.parentNode.insertBefore(wrap,input);wrap.append(input);
      const closing=document.createElement('button');closing.className='closing-filter';closing.innerHTML='◷ &nbsp; Closing soon';tools.insertBefore(closing,tools.children[1]);
      closing.onclick=()=>{closing.classList.toggle('active');qa('#todayList .opp-row').forEach((row,i)=>row.hidden=closing.classList.contains('active')&&i>2)};
    }
    const update=()=>{const checked=qa('#todayList input[type="checkbox"]:checked'),bar=q('#selectionBar'),button=q('#sendReview');bar?.classList.toggle('show',checked.length>0);if(q('#selectedCount'))q('#selectedCount').textContent=`${checked.length} selected`;if(button)button.disabled=!checked.length};
    q('#todayList')?.addEventListener('change',update);
    const old=q('#sendReview');if(old&&!old.dataset.fixed){const fresh=old.cloneNode(true);fresh.dataset.fixed='1';old.replaceWith(fresh);fresh.onclick=()=>{const count=qa('#todayList input[type="checkbox"]:checked').length;if(!count)return;say(`${count} opportunities sent to human review.`);qa('#todayList input[type="checkbox"]:checked').forEach(x=>x.checked=false);update()}}
  }

  function tuneDashboard(){
    const funnel=q('.master-funnel');if(funnel)funnel.innerHTML=[['Identified','214','100%',100],['Relevant','68','31.8%',72],['Pursued','31','14.5%',52],['Submitted','25','11.7%',43],['Awarded','7','3.3%',25]].map(x=>`<div style="--w:${x[3]}%"><span>${x[0]}</span><i><u></u></i><b>${x[1]}</b><em>${x[2]}</em></div>`).join('');
    const card=q('.deadline-card');if(card)card.innerHTML=`<header><div><b>SUBMISSION DEADLINES</b><small>Upcoming proposals by month</small></div><small>Sep 2025 – Feb 2026</small></header><div class="deadline-bars">${[['Sep',4],['Oct',7],['Nov',11],['Dec',6],['Jan',8],['Feb',5]].map(([m,n])=>`<div><b>${n}</b><i style="--h:${n/11*100}%"></i><span>${m}</span></div>`).join('')}</div><p class="deadline-insight"><b>November is the peak month.</b> Plan reviewer capacity before the October pipeline closes.</p>`;
  }

  function pipelineMode(){const active=q('#pipelineMetrics button.active'),view=q('#pipelineView');view?.classList.toggle('proposal-mode',active?.dataset.pstage==='Proposal')}

  const priorDetail=window.openDetail;
  window.openDetail=function(opportunity){
    priorDetail(opportunity);
    const origin=q('.record-origin');
    if(origin) origin.dataset.country=opportunity.country||'';
  };

  const priorShow=window.showView;
  window.showView=function(name){priorShow(name);if(name==='criteria')renderNotebook();if(name==='dashboard')tuneDashboard();if(name==='pipeline')setTimeout(pipelineMode)};
  qa('.navlinks button').forEach(b=>b.onclick=()=>window.showView(b.dataset.view));
  q('#pipelineMetrics')?.addEventListener('click',()=>setTimeout(pipelineMode));
  tuneToday();tuneDashboard();pipelineMode();renderNotebook();
})();
